-
  position: '1'
  name: 'USA Toyz Play Kitchen Set'
-
  position: '2'
  name: 'American Plastic Toys Baker''s Kitchen Playset'
-
  position: '3'
  name: 'Uptown Natural Kitchen'
-
  position: '4'
  name: 'Peppa''s Little Kitchen Deluxe Feature Role-Play'
-
  position: '5'
  name: 'Step2 Little Bakers Kitchen Playset'
-
  position: '6'
  name: 'Melissa & Doug Wooden Chef''s Pretend Play Toy Kitchen'
-
  position: '7'
  name: 'Little Tikes Cook ''n Learn Smart Kitchen'
-
  position: '8'
  name: 'Teamson Kids - Little Chef Florence Classic Kids Play Kitchen'
